### ISSUE TITLE
Planning

### ISSUE THREAD

**Issue by pcreglow** [pcreglow/OC-Run#1]
## [Orlando City Run](https://oc-run.firebaseapp.com) - Planning

[**User Stories**](https://github.com/pcreglow/OC-Run/wiki/User-Stories)

**MVP**
- [ ] A runner can select a neighborhood so that they can view running routes in that neighborhood.
- [ ] A runner can select a route from a list of routes in a neighborhood so that they can view information about that route.
- [ ] A runner can view a route map for a selected route.
- [ ] A runner can view a photo carousel for a selected route.
- [ ] A runner can read a description of a selected route.
- [ ] A runner can read data list items for a selected route so that they are aware of amenities, distance, and conditions.
- [ ] A runner can submit comments about a selected route.

**Stretch**
- [ ] A runner can submit a form so that they can post information about a running group, event, or activity taking place in a neighborhood.
- [ ] A runner can submit a route recommendation.
- [ ] A runner can click a social media icon to "follow" and "like" Orlando City Run social media accounts.
- [x] [**release/0.0.0--yak-shaving**](https://github.com/pcreglow/OC-Run/issues/2)
- [x] [**release/0.1.0--views-routes**](https://github.com/pcreglow/OC-Run/issues/19)
- [x] [**release/0.2.0--route-scaffolding**](https://github.com/pcreglow/OC-Run/issues/40)
- [x] [**release/0.3.0--firebase-data**](https://github.com/pcreglow/OC-Run/issues/58)
- [x] [**release/1.0.0--minimum-viable-product**](https://github.com/pcreglow/OC-Run/issues/90)
- [x] [**release/1.1.0--submit-running-event**](https://github.com/pcreglow/OC-Run/issues/102)
- [x] [**release/1.2.0--style**](https://github.com/pcreglow/OC-Run/issues/124)
- [x] [**release/1.2.1--tabs-fix**](https://github.com/pcreglow/OC-Run/issues/128)
- [ ] **Minimum Viable Product (MVP)**
  - [x] Scaffolding
    - [x] feature/main-header-scaffolding
    - [x] feature/main-tabs-scaffolding
    - [x] feature/main-photo-scaffolding
    - [x] feature/main-description-scaffolding
    - [x] feature/views-routes
    - [x] feature/route-map-scaffolding
    - [x] feature/route-description-scaffolding
    - [x] feature/route-photo-scaffolding
    - [x] feature/route-categories-scaffolding
    - [x] feature/route-activity-scaffolding
    - [x] feature/route-comment-scaffolding
    - [x] feature/route-reposition
    - [x] feature/route-events
    - [x] feature/route-comments
    - [x] feature/about-scaffolding
    - [x] feature/views-routes-correction
    - [x] feature/route-duplicate
    - [x] feature/refactor-correction
  - [ ] Firebase
    - [x] Data Model 
    - [ ] Lake Eola - Route 
    - [ ] Mills 50 - Route 
    - [ ] Lake Eola - Route 2 
    - [ ] Mills 50 - Route 2
    - [ ] Lake Eola - Route 3
    - [ ] Mills 50 - Route 3
    - [ ] Lake Eola - Events
    - [ ] Mills 50 - Events
  - [x] Placeholder
    - [x] feature/json-data
    - [x] feature/route-description-placeholder
    - [x] feature/route-categories-placeholder
    - [x] feature/route-comment-placeholder
    - [x] feature/route-submit-comment
    - [x] feature/route2-submit-comment
    - [x] feature/route3-submit-comment
    - [x] feature/mills-description-placeholder
    - [x] feature/mills-categories-placeholder
    - [x] feature/mills-comment-placeholder
    - [x] feature/mills-submit-comment
    - [x] feature/mills2-submit-comment
    - [x] feature/mills3-submit-comment
  - [x] Select A Route
    - [x] feature/route-tabs-scaffolding
    - [x] feature/route-views-scaffolding
    - [x] feature/route-lake-eola2
    - [x] feature/route-lake-eola3
    - [x] feature/mills-tabs-scaffolding
    - [x] feature/mills-views-scaffolding
    - [x] feature/mills-route2
    - [x] feature/mills-route3
  - [ ] Refactor
    - [x] feature/views-comments-placement
    - [x] feature/remove-events
    - [x] feature/photo-carousel
    - [x] feature/tab-routes
    - [ ] feature/header-mobile
    - [ ] feature/route-mobile
    - [ ] feature/mills-mobile
    - [ ] feature/events-mobile
  - [ ] Photos
    - [x] feature/lake-eola-photos
    - [ ] feature/mills-fifty-photos
    - [x] feature/home-photo
    - [x] feature/photo-carousel-firebase
  - [x] Styles
    - [x] feature/route-style
    - [x] feature/comments-style
    - [x] feature/header-tabs-style
    - [x] feature/header-logo-style
    - [x] feature/events-style
    - [x] feature/about-style
    - [x] feature/home-style
  - [x] Events Form
    - [x] feature/route-events-scaffolding
    - [x] feature/mills-events-scaffolding
    - [x] feature/route-events-form
    - [x] feature/mills-events-form
- [ ] **BEAST Mode:** Stretch Goals
  - [ ] Maps
    - [ ] feature/google-maps-api
    - [ ] feature/custom-google-maps 
  - [ ] Views
    - [ ] feature/dynamic-views
  - [ ] Authentication
    - [ ] feature/facebook-authentication
  - [ ] Social Media
    - [ ] feature/main-facebook-icon
    - [ ] feature/main-instagram-icon
    - [ ] feature/main-twitter-icon
  
  **Deadlines:**
  - [x] **First Monday - July 6:** Project Pitch
  - [x] **First Wednesday - July 8:** Planning
  - [x] **First Friday - July 10:** Yak Shaving (0.0.0)
  - [x] **Second Monday - July 13:** First Features
  - [x] **Second Wednesday - July 15:** First Release (>0.1.0)
  - [x] **Second Friday - July 17:** Mostly MVP (1.0.0)
  - [x] **FINAL Monday - July 20:** Final Release (1.Y.0)
  - [ ] **FINAL Wednesday - July 22:** Code Freeze (1.Y.Z)
  - [ ] **FINAL Friday - July 24:** Project Presentation!

**Comment by pcreglow** [comment]
![ocrun_main](https://cloud.githubusercontent.com/assets/11493983/8553123/4c0d0e60-24af-11e5-9b46-a291bb172433.png)

**Comment by pcreglow** [comment]
![ocrun_main](https://cloud.githubusercontent.com/assets/11493983/8600302/544ec1d8-2633-11e5-829c-4b0a370a623e.png)

**Comment by pcreglow** [comment]
![ocrun_route](https://cloud.githubusercontent.com/assets/11493983/8600309/5a18fd22-2633-11e5-8772-9a70e64f5f2f.png)

**Comment by pcreglow** [comment]
https://oc-run.firebaseapp.com/
